In [33]:
import pandas as pd
import numpy as np
from AmaFree import AdvancedScorecardBuilder as asb

In [54]:
df = pd.read_csv('abt_app (1).csv',sep='\t')

In [55]:
df.head()

,cid,aid,product,period,act_age,act_cc,act_loaninc,app_income,app_loan_amount,app_n_installments,...,default3,default6,default9,default12,default_cross3,default_cross6,default_cross9,default_cross12,cross_app_loan_amount,cross_app_n_installments
0,1330,css1975010100098,css,197501,45.0,0.326905,1.530456,3267.0,5000.0,24.0,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2179,css1975010100120,css,197501,42.0,0.538908,2.903600,1722.0,5000.0,24.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,146,css1975010200014,css,197501,59.0,0.543742,3.364738,1486.0,5000.0,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5000.0,24.0
3,479,css1975010200047,css,197501,63.0,0.587702,3.236246,1545.0,5000.0,24.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4514,css1975010200151,css,197501,48.0,0.436407,1.506932,3318.0,5000.0,24.0,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
delete_cols = ['period','cross_aid','default_cross3','aid','cid','default3','default6','default9','default_cross3','default_cross6','default_cross9','default_cross12']
df=df.drop(delete_cols,axis=1)#usuwamy zbędne kolumny

In [57]:
#są błędne dane w targecie - default12
df = df.dropna(subset=['default12']) 
df['default12'] = df['default12'].astype(np.int64)
#df.select_dtypes(include=['object'])
test = asb(df,'default12')

feature product removed - one value in column
feature app_loan_amount removed - one value in column
feature app_n_installments removed - one value in column
feature app_installment removed - one value in column
feature app_char_branch removed - one value in column
feature act_cus_active removed - one value in column
feature decision removed - one value in column

In [58]:
test.fit(n_category=6, n_features=9)

You have less then 0.05 empty values in ags3_Mean_CMaxA_Days. I change them by mean value
You have less then 0.05 empty values in ags3_Max_CMaxA_Days. I change them by mean value
You have less then 0.05 empty values in ags3_Min_CMaxA_Days. I change them by mean value
You have less then 0.05 empty values in agr3_Mean_CMaxA_Due. I change them by mean value
You have less then 0.05 empty values in agr3_Max_CMaxA_Due. I change them by mean value
You have less then 0.05 empty values in agr3_Min_CMaxA_Due. I change them by mean value
You have less then 0.05 empty values in ags6_Mean_CMaxA_Days. I change them by mean value
You have less then 0.05 empty values in ags6_Max_CMaxA_Days. I change them by mean value
You have less then 0.05 empty values in ags6_Min_CMaxA_Days. I change them by mean value
I removed agr9_Min_CMaxI_Due - no binns
I removed ags9_Min_CMaxI_Due - no binns
I removed agr12_Max_CMaxI_Days - no binns
I removed agr12_Min_CMaxI_Due - no binns
I removed ags12_Min_CMaxI_Due - no binns
I removed agr12_Min_CMaxC_Due - no binns
I removed ags12_Min_CMaxC_Due - no binns
I removed agr12_Min_CMaxA_Due - no binns

In [59]:
test.get_scorecard()

,label,variable,score
0,(not missing) and act_age <= 45.5,act_age,12
1,45.5 < act_age <= 60.5,act_age,20
2,64.5 < act_age <= 66.5,act_age,23
3,60.5 < act_age <= 64.5,act_age,27
4,66.5 < act_age <= 80.5,act_age,28
5,80.5 < act_age,act_age,43
6,app_char_job_code = Contract,app_char_job_code,12
7,app_char_job_code = Owner company,app_char_job_code,60
8,app_char_job_code = Permanent,app_char_job_code,76
9,app_char_job_code = Retired,app_char_job_code,80
10,1.498 < act_call_cc,act_call_cc,12
11,1.266 < act_call_cc <= 1.498,act_call_cc,34
12,0.988 < act_call_cc <= 1.163,act_call_cc,39
13,0.44 < act_call_cc <= 0.988,act_call_cc,48
14,1.163 < act_call_cc <= 1.266,act_call_cc,53
15,(not missing) and act_call_cc <= 0.44,act_call_cc,56
16,0.5 < act_ccss_n_statC <= 1.5,act_ccss_n_statC,12
17,1.5 < act_ccss_n_statC <= 3.5,act_ccss_n_statC,19
18,act_ccss_n_statC <= 0.5,act_ccss_n_statC,20
19,3.5 < act_ccss_n_statC <= 7.5,act_ccss_n_statC,25
20,missing,act_ccss_n_statC,46
21,7.5 < act_ccss_n_statC <= 16.5,act_ccss_n_statC,75
22,16.5 < act_ccss_n_statC,act_ccss_n_statC,124
23,missing,agr3_Mean_CMaxI_Days,12
24,12.167 < agr3_Mean_CMaxI_Days <= 12.5,agr3_Mean_CMaxI_Days,18
25,11.167 < agr3_Mean_CMaxI_Days <= 12.167,agr3_Mean_CMaxI_Days,22
26,agr3_Mean_CMaxI_Days <= 10.5,agr3_Mean_CMaxI_Days,25
27,12.5 < agr3_Mean_CMaxI_Days <= 14.167,agr3_Mean_CMaxI_Days,26
28,14.167 < agr3_Mean_CMaxI_Days,agr3_Mean_CMaxI_Days,29
29,10.5 < agr3_Mean_CMaxI_Days <= 11.167,agr3_Mean_CMaxI_Days,32
30,missing,agr3_Min_CMaxI_Days,12
31,9.5 < agr3_Min_CMaxI_Days <= 10.5,agr3_Min_CMaxI_Days,20
32,agr3_Min_CMaxI_Days <= 7.5,agr3_Min_CMaxI_Days,23
33,10.5 < agr3_Min_CMaxI_Days <= 11.5,agr3_Min_CMaxI_Days,23
34,11.5 < agr3_Min_CMaxI_Days,agr3_Min_CMaxI_Days,26
35,7.5 < agr3_Min_CMaxI_Days <= 8.5,agr3_Min_CMaxI_Days,27
36,8.5 < agr3_Min_CMaxI_Days <= 9.5,agr3_Min_CMaxI_Days,33
37,1.5 < ags3_Mean_CMaxA_Due,ags3_Mean_CMaxA_Due,12
38,1.167 < ags3_Mean_CMaxA_Due <= 1.5,ags3_Mean_CMaxA_Due,33
39,0.833 < ags3_Mean_CMaxA_Due <= 1.167,ags3_Mean_CMaxA_Due,51
40,0.417 < ags3_Mean_CMaxA_Due <= 0.833,ags3_Mean_CMaxA_Due,62
41,0.167 < ags3_Mean_CMaxA_Due <= 0.417,ags3_Mean_CMaxA_Due,77
42,(not missing) and ags3_Mean_CMaxA_Due <= 0.167,ags3_Mean_CMaxA_Due,84
43,14.775 < ags12_Mean_CMaxI_Days,ags12_Mean_CMaxI_Days,12
44,ags12_Mean_CMaxI_Days <= 11.866,ags12_Mean_CMaxI_Days,14
45,missing,ags12_Mean_CMaxI_Days,16
46,11.866 < ags12_Mean_CMaxI_Days <= 13.211,ags12_Mean_CMaxI_Days,19
47,13.348 < ags12_Mean_CMaxI_Days <= 14.042,ags12_Mean_CMaxI_Days,21
48,14.042 < ags12_Mean_CMaxI_Days <= 14.775,ags12_Mean_CMaxI_Days,29
49,13.211 < ags12_Mean_CMaxI_Days <= 13.348,ags12_Mean_CMaxI_Days,37

In [60]:
test.model_info_

{'coef': {'act_age': 0.8586200105588485,
  'app_char_job_code': 1.1984406041732816,
  'act_call_cc': 1.289516447723379,
  'act_ccss_n_statC': 1.0466335089404002,
  'agr3_Mean_CMaxI_Days': 0.9643714204551989,
  'agr3_Max_CMaxI_Days': -1.537977590834453,
  'agr3_Min_CMaxI_Days': 0.9604778528107693,
  'ags3_Mean_CMaxA_Due': 0.8718321438721248,
  'ags12_Mean_CMaxI_Days': 1.1081935090790473},
 'p_value': {'act_age': 0.0,
  'app_char_job_code': 0.0,
  'act_call_cc': 0.0,
  'act_ccss_n_statC': 0.0,
  'agr3_Mean_CMaxI_Days': 0.0,
  'agr3_Max_CMaxI_Days': 0.0,
  'agr3_Min_CMaxI_Days': 0.0,
  'ags3_Mean_CMaxA_Due': 0.0,
  'ags12_Mean_CMaxI_Days': 0.0},
 'features': ['act_age',
  'app_char_job_code',
  'act_call_cc',
  'act_ccss_n_statC',
  'agr3_Mean_CMaxI_Days',
  'agr3_Max_CMaxI_Days',
  'agr3_Min_CMaxI_Days',
  'ags3_Mean_CMaxA_Due',
  'ags12_Mean_CMaxI_Days'],
 'model': 'LogisticRegressionCV',
 'gini': 0.6634032455448857,
 'acc': 0.7742480567759378,
 'Precision': 0.7938988095238095,
 'Recall': 0.7318244170096022,
 'F1': 0.7615988579586009,
 'intercept': array([0.25250802])}